---
authentication: true # Set to false to disable authentication
influxdb:
  enabled: true
  host_tag: 'speedtest-tracker'
  retention: '30d'
notifications:
  channels:
    discord:
      webhook_url: null # Set as null to disable
    slack:
      webhook_url: null # Set as null to disable
speedtest:
  enabled: true
  schedule: '*/60 * * * *' # every hour
  ookla_server_id: null # specify a server ID to use a sepecific server
tz: 'UTC'
